// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvmsszzsehvcvlxneufg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2bXNzenpzZWh2Y3ZseG5ldWZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NjU1MTksImV4cCI6MjA2ODM0MTUxOX0.f1sqzK5Bm0FwdpR30l19fwbN51yU9hHVLs8Gwt321Gk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});